# Generated by Django 5.2.8 on 2025-11-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlucosaRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor_mg_dl", models.PositiveSmallIntegerField()),
                ("medido_en", models.DateTimeField()),
                ("fuente", models.CharField(default="manual", max_length=20)),
                ("notas", models.CharField(blank=True, max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glucemias",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-medido_en"],
            },
        ),
    ]
