# Generated by Django 5.2.8 on 2025-11-11 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "tipo_diabetes",
                    models.CharField(
                        choices=[
                            ("T1", "Tipo 1"),
                            ("T2", "Tipo 2"),
                            ("G", "Gestacional"),
                            ("O", "Otra"),
                        ],
                        default="T1",
                        max_length=2,
                    ),
                ),
                ("objetivo_glucosa_min", models.PositiveSmallIntegerField(default=80)),
                ("objetivo_glucosa_max", models.PositiveSmallIntegerField(default=140)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paciente",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
