# Generated by Django 5.2.8 on 2025-11-12 17:33

import django.db.models.deletion
import kits.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True, default="")),
                (
                    "token_publico",
                    models.CharField(
                        default=kits.models.gen_token, max_length=64, unique=True
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kits",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="VerificacionKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[("privado", "privado"), ("qr", "qr")],
                        default="qr",
                        max_length=10,
                    ),
                ),
                ("resultado_ok", models.BooleanField(default=False)),
                ("faltantes_json", models.JSONField(default=dict)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verificaciones",
                        to="kits.kit",
                    ),
                ),
                (
                    "verificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="ElementoKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etiqueta", models.CharField(max_length=120)),
                ("cantidad_requerida", models.PositiveIntegerField(default=1)),
                ("unidad", models.CharField(default="u", max_length=16)),
                (
                    "kit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elementos",
                        to="kits.kit",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "unique_together": {("kit", "etiqueta")},
            },
        ),
    ]
