# Generated by Django 5.2.8 on 2025-11-12 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INS", "Insulina"),
                            ("TIR", "Tiras"),
                            ("AGU", "Agujas"),
                            ("SEN", "Sensor"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("stock_actual", models.IntegerField(default=0)),
                ("stock_minimo", models.IntegerField(default=0)),
                ("unidad", models.CharField(default="u", max_length=20)),
                ("caduca_en", models.DateField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insumos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovimientoInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("cantidad", models.IntegerField()),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("compra", "Compra"),
                            ("uso", "Uso"),
                            ("ajuste", "Ajuste"),
                            ("caducidad", "Caducidad"),
                        ],
                        default="uso",
                        max_length=20,
                    ),
                ),
                ("nota", models.CharField(blank=True, max_length=200)),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="insumos.insumo",
                    ),
                ),
            ],
            options={
                "ordering": ("-fecha",),
            },
        ),
    ]
